addons:
  ssh_known_hosts: wwelo.com
before_install:
  - openssl aes-256-cbc -K $encrypted_5c7863196bee_key -iv $encrypted_5c7863196bee_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
jobs:
  include:
    - stage: "Build and upload"
      script: 
        - docker build . -t wwelo
        - docker save --output wwelo_image.tar wwelo
        - gzip wwelo_image.tar
        - rsync -aP wwelo_image.tar.gz mcgavin@wwelo.com:~
        - rsync -aP docker-compose/prod.yml mcgavin@wwelo.com:docker-compose.yml
    - stage: "Deploy"
      script:
        - ssh mcgavin@wwelo.com gzip -d wwelo_image.tar.gz
        - ssh mcgavin@wwelo.com docker load wwelo_image.tar
        - ssh mcgavin@wwelo.com docker-compose up
