language: elixir
elixir:
- '1.6'
otp_release:
- '20.0'
addons:
  ssh_known_hosts: wwelo.com
before_install:
- openssl aes-256-cbc -K $encrypted_5c7863196bee_key -iv $encrypted_5c7863196bee_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
script:
- mix edeliver build upgrade --from=32d8723db6926e58bacfb9c7084abab8a10b9305 --verbose
- mix edeliver deploy upgrade to production --verbose
