language: elixir
elixir:
- '1.6'
otp_release:
- '20.0'
script:
- mix edeliver upgrade production --verbose
before_install:
- openssl aes-256-cbc -K $encrypted_5c7863196bee_key -iv $encrypted_5c7863196bee_iv
  -in deploy_rsa.enc -out deploy_rsa -d
